
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Megha
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/78948.png"))); // NOI18N
        jButton1.setText("Librarian");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 150, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school-student-icon-png-2-Transparent-Images.png"))); // NOI18N
        jButton2.setText("Student ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setText("Choose  one option from the below...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 620, 49));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 58)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/81Dm7WUxFXL.png"))); // NOI18N
        jLabel2.setText(" Welcome To Our Library");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 980, 160));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/services.png"))); // NOI18N
        jButton3.setText("Our Services");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, -1, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutus.png"))); // NOI18N
        jButton4.setText("About us");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, -1, 40));

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T&C.png"))); // NOI18N
        jButton5.setText("Term & Conditions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Studentlogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
         new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"LIBRARY MANAGEMENT SYSTEM MAJOR FUNCTIONALITIES\n" +
"Features\n" +
 "Admin\n" +
"1 Manage books\n" +
"2 Issue/Return statistics\n" +
"3 Manage students\n" +
"4 Issue books\n" +
"5 Return books\n" +
"6 Admin login\n" +
"7 view request\n" +  
"8 New book\n" +
"9 New student\n" +
"10 List of available book/students\n" +
 "Student\n" +
"1 Student login\n" +
"2 Available books list\n" +
"3 Return book\n" +                
"4 Send request to issue books\n" +
"To start executing a Java Project, makes sure that you have \n" +
"NetBeans IDE or any platform of Java installed in your computer.\n");        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"ABOUT THE PROJECT\n" +
"This 2022 Library Management System Project in Java was created with the help of JAVA, \n" +
"MySQL Connector, and MySQL Database. \n" +
"This Library Management System is a simple project for library management.\n" +
"A Java Library Management System is a software program built on the Java platform and based on \n" +
"the MySQL database design. It is beneficial for libraries in schools and other educational \n" +
"institutions to employ a computerized system to handle and maintain data in databases.\n" +
"Users do not need to search the entire library for a book when using this Library Management \n" +
"System Java; the program displays a list of accessible books.\n" +
"The main features of this Library Management System Java is that students can borrow all of the \n" +
"books in the library. In addition, students can return borrowed books to the library.\n" +
"Furthermore, the application successfully retains the details of users/students to whom books \n" +
"have been issued, as well as the date of issue and date of return.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"TERMS & CONDITIONS \n" +
"This privacy notice discloses the privacy practices for our LMS This privacy notice applies solely to\n" +
"information collected by this website. It will notify you of the following:\n" +
"What personally identifiable information is collected from you through the website,\n" +
"how it is used and with whom it may be shared.\n" +
"What choices are available to you regarding the use of your data.\n" +
"The security procedures in place to protect the misuse of your information.\n" +
"How you can correct any inaccuracies in the information.\n" +
"Information Collection, Use, and Sharing \n" +
"We are the sole owners of the information collected on this site. We only have access to/collect \n" +
"information that you voluntarily give us via email or other direct contact from you \n" +
"We will not sell or rent this information to anyone. \n" +
"We will use your information to respond to you, regarding the reason you contacted us. \n" +
"We will not share your information with any third party outside of our organization, \n" + 
"other than as necessary to fulfill your request, e.g. to ship an order.\n" +
"Unless you ask us not to, we may contact you via email in the future to tell you about specials, \n" + 
"new products or services, or changes to this privacy policy.\n" +
"Your Access to and Control Over Information \n" +
"See what data we have about you, if any.\n" +
"Change/correct any data we have about you.\n" +
"Have us delete any data we have about you.\n" +
"Express any concern you have about our use of your data.\n" +
"Security \n" +
"We take precautions to protect your information. When you submit sensitive information via the website, \n" +
"your information is protected both online and offline.\n" +
"Wherever we collect sensitive information (such as credit card data), that information is encrypted and \n" +
"transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and \n" +
"looking for \"https\" at the beginning of the address of the Web page.\n" +
"While we use encryption to protect sensitive information transmitted online, we also protect your information offline.\n" +
"Only employees who need the information to perform a specific job (for example, billing or customer service)\n" +
"are granted access to personally identifiable information. The computers/servers in which we store personally \n" +
"identifiable information are kept in a secure environment.\n" +
"If you feel that we are not abiding by this privacy policy, you should contact us via Email \n"       
        );
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
